# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[1,2,3]])


# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[1,2,3],[1,2,3]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.size, a2.ndim, a2.dtype, type(a2)

((2, 3), 6, 2, dtype('int64'), numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((1, 3, 3), 3, dtype('int64'), 9, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a1_df = pd.DataFrame(a1)
a1_df

0
0  1
1  2
2  3

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
arr = np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_int_array = np.random.randint(10, size=(7,2))
rand_int_array

array([[6, 3],
       [7, 7],
       [4, 4],
       [5, 8],
       [7, 9],
       [6, 8],
       [0, 5]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.seed(0)
rand_float_array = np.random.rand(3,5)
rand_float_array

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [12]:
# Set the random seed to 42
np.random.seed(42)


# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_array_int_2 = np.random.randint(10, size=(4,6))
rand_array_int_2


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_array_int_3 = np.random.randint(10, size=(3,7))


# Find the unique numbers in the array you just created
np.unique(rand_array_int_3)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [14]:
# Find the 0'th index of the latest array you created
np.indices([0])

array([], shape=(1, 0), dtype=int64)

In [15]:
# Get the first 2 rows of latest array you created
rand_array_int_3
rand_array_int_3.shape
rand_array_int_3[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [16]:
# Get the first 2 rows of latest array you created
rand_array_int_3[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
rand_array_int_3[1]

array([2, 4, 2, 6, 4, 8, 6])

In [28]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array = np.random.randint(10, size=(3,5))
ones = np.ones((3,5))
random_array, ones

(array([[4, 2, 7, 5, 2],
        [0, 2, 4, 2, 0],
        [4, 9, 6, 6, 8]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [31]:
# Add the two arrays together
np.add(random_array, ones)

array([[ 5.,  3.,  8.,  6.,  3.],
       [ 1.,  3.,  5.,  3.,  1.],
       [ 5., 10.,  7.,  7.,  9.]])

In [33]:
# Create another array of ones of shape (5, 3)
ones_1 = np.ones((5,3))
ones_1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# Try add the array of ones and the other most recent array together
np.add(ones, ones_1)

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [36]:
# Create another array of ones of shape (3, 5)
ones_2 = np.ones((3,5))
ones_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
# Subtract the new array of ones from the other most recent array
np.subtract(ones_2, random_array)

array([[-3., -1., -6., -4., -1.],
       [ 1., -1., -3., -1.,  1.],
       [-3., -8., -5., -5., -7.]])

In [44]:
# Multiply the ones array with the latest array
np.multiply(ones_2, random_array)

array([[4., 2., 7., 5., 2.],
       [0., 2., 4., 2., 0.],
       [4., 9., 6., 6., 8.]])

In [45]:
# Take the latest array to the power of 2 using '**'
random_array**2

array([[16,  4, 49, 25,  4],
       [ 0,  4, 16,  4,  0],
       [16, 81, 36, 36, 64]])

In [46]:
# Do the same thing with np.square()
np.square(random_array)

array([[16,  4, 49, 25,  4],
       [ 0,  4, 16,  4,  0],
       [16, 81, 36, 36, 64]])

In [47]:
# Find the mean of the latest array using np.mean()
np.mean(random_array)

4.066666666666666

In [48]:
# Find the maximum of the latest array using np.max()
np.max(random_array)

9

In [49]:
# Find the minimum of the latest array using np.min()
np.min(random_array)

0

In [50]:
# Find the standard deviation of the latest array
np.std(random_array)

2.6699979192667715

In [51]:
# Find the variance of the latest array
np.var(random_array)

7.12888888888889

In [54]:
# Reshape the latest array to (3, 5, 1)
np.reshape(random_array, (3,5,1))

array([[[4],
        [2],
        [7],
        [5],
        [2]],

       [[0],
        [2],
        [4],
        [2],
        [0]],

       [[4],
        [9],
        [6],
        [6],
        [8]]])

In [55]:
# Transpose the latest array
random_array.T

array([[4, 0, 4],
       [2, 2, 9],
       [7, 4, 6],
       [5, 2, 6],
       [2, 0, 8]])

What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [34]:
# Perform a dot product on the two newest arrays you created


In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [36]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [39]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='


In [41]:
# Find which elements of the first array are greater than 7


In [42]:
# Which parts of each array are equal? (try using '==')


In [43]:
# Sort one of the arrays you just created in ascending order


In [44]:
# Sort the indexes of one of the arrays you just created


In [45]:
# Find the index with the maximum value in one of the arrays you've created


In [46]:
# Find the index with the minimum value in one of the arrays you've created


In [47]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created


In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.